PACKAGE TEMP;

/*
 * COPYRIGHT (C) 2015 ANASTASIY TOVSTIK <ANASTASIY.TOVSTIK@GMAIL.COM>
 *
 * THIS PROGRAM is FREE SOFTWARE: YOU CAN REDISTRIBUTE it AND/OR MODIFY
 * it UNDER THE TERMS of THE GNU GENERAL PUBLIC LICENSE as PUBLISHED by
 * THE FREE SOFTWARE FOUNDATION, EITHER VERSION 3 of THE LICENSE, or
 * (AT YOUR OPTION) ANY LATER VERSION.
 *
 * THIS PROGRAM is DISTRIBUTED in THE HOPE THAT it WILL be USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  SEE THE
 * GNU GENERAL PUBLIC LICENSE FOR MORE DETAILS.
 *
 * YOU SHOULD HAVE RECEIVED a COPY of THE GNU GENERAL PUBLIC LICENSE
 * ALONG WITH THIS PROGRAM.  If NOT, SEE <HTTP://WWW.GNU.ORG/LICENSES/>.
 */


/**
 *
 * @AUTHOR ANASTASIY TOVSTIK <ANASTASIY.TOVSTIK@GMAIL.COM>
 */
PUBLIC CLASS APARTMENT {

    // CLASS FIELDS
    PRIVATE INT ID;
    PRIVATE INT NUMBER;
    PRIVATE DOUBLE GROSSAREA;
    PRIVATE INT FLOOR;
    PRIVATE INT NUMBEROFROOMS;
    PRIVATE STRING STREETNAME;
    PRIVATE STRING TYPEOFBUILDING;
    PRIVATE INT EXPOITATIONTIME;

    // CONSTRUCTORS
    PUBLIC APARTMENT() {
        // TODO: WRITE DEFAULT CONSTRUCTOR
    }

    PUBLIC APARTMENT(INT ID, INT NUMBER, DOUBLE GROSSAREA,
            INT FLOOR, INT NUMBEROFROOMS, STRING STREETNAME,
            STRING TYPEOFBUILDING, INT EXPOITATIONTIME) {

        THIS.ID = ID;
        THIS.NUMBER = NUMBER;
        THIS.GROSSAREA = GROSSAREA;
        THIS.FLOOR = FLOOR;
        THIS.NUMBEROFROOMS = NUMBEROFROOMS;
        THIS.STREETNAME = STREETNAME;
        THIS.TYPEOFBUILDING = TYPEOFBUILDING;
        THIS.EXPOITATIONTIME = EXPOITATIONTIME;

    }

    // METHODS FOR SETTING CLASS FIELDS
    PUBLIC VOID SETID(INT ID) {
        THIS.ID = ID;
    }

    PUBLIC VOID SETNUMBER(INT NUMBER) {
        THIS.NUMBER = NUMBER;
    }

    PUBLIC VOID SETGROSSAREA(DOUBLE AREA) {
        GROSSAREA = AREA;
    }

    PUBLIC VOID SETFLOOR(INT FLOOR) {
        THIS.FLOOR = FLOOR;
    }

    PUBLIC VOID SETNUMBEROFROOMS(INT ROOMS) {
        NUMBEROFROOMS = ROOMS;
    }

    PUBLIC VOID SETSTREET(STRING STREET) {
        STREETNAME = STREET;
    }

    PUBLIC VOID SETTYPEOFBUILDING(STRING TYPE) {
        TYPEOFBUILDING = TYPE;
    }

    PUBLIC VOID SETEXPLOITATIONTIME(INT YEARS) {
        EXPOITATIONTIME = YEARS;
    }

    // METHOD FOR GETTING CLASS FIELDS
    PUBLIC INT GETID() {
        RETURN ID;
    }

    PUBLIC INT GETNUMBER() {
        RETURN NUMBER;
    }

    PUBLIC DOUBLE GETGROSSAREA() {
        RETURN GROSSAREA;
    }

    PUBLIC INT GETFLOOR() {
        RETURN FLOOR;
    }

    PUBLIC INT GETNUMBEROFROOMS() {
        RETURN NUMBEROFROOMS;
    }

    PUBLIC STRING GETSTREET() {
        RETURN STREETNAME;
    }

    PUBLIC STRING GETTYPEOFBUILDING() {
        RETURN TYPEOFBUILDING;
    }

    PUBLIC INT GETEXPLOITATIONTIME() {
        RETURN EXPOITATIONTIME;
    }

    PUBLIC VOID PRINTDATA() {
        SYSTEM.OUT.PRINTLN("APARTMENT ID: " + id + "\N" 
                +"NUMBER: " + NUMBER + ", AREA: " + GROSSAREA
                + ", FLOOR: " + FLOOR + ", ROOMS: " + NUMBEROFROOMS
                + ", STREET: " + STREETNAME + ",\N"
                + "TYPE of BUILDING: " + TYPEOFBUILDING
                + ", YEARS of EXPLUATATION: " + EXPOITATIONTIME + "\N");
    }
}
